version: 2
jobs:
    build:
        machine: True
        working_directory: ~/test-containers
        steps:
          - checkout
          - run:
                name: install dependencies
                command: |
                    sudo add-apt-repository ppa:deadsnakes/ppa -y
                    sudo apt-get update
                    sudo apt-get install -y python3.6 python3.6-venv
                    /usr/bin/python3.6  -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
          - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    python tests/test-test-containers.py
